version: '3.8'

services:
  plate-it-forward-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]